		<AffiliateOptions_Update>
			<Active>No</Active>
			<ApplicationStatus>Approved</ApplicationStatus>
			<DefaultCommissionHit>0.0000</DefaultCommissionHit>
			<DefaultCommissionPercentOfOrder>0.00</DefaultCommissionPercentOfOrder>
			<DefaultCommissionOrderFlatFee>0.00</DefaultCommissionOrderFlatFee>
			<PayoutThreshold>0.00</PayoutThreshold>
			<LinkImage></LinkImage>
			<LinkText></LinkText>
			<Terms></Terms>
		</AffiliateOptions_Update>