        <CustomerFields_Update>
            <Billing>Hidden</Billing>
            <FirstName>Required</FirstName>
            <LastName>Required</LastName>
            <Email>Required</Email>
            <Phone>Required</Phone>
            <Fax>Hidden</Fax>
            <Company>Optional</Company>
            <Address>Required</Address>
            <City>Required</City>
            <State>Required</State>
            <Zip>Required</Zip>
            <Country>Hidden</Country>
        </CustomerFields_Update>